### ISSUE TITLE
Nuget Publishing should switch from LicenseUrl to License.

### ISSUE THREAD

**Issue by corthon** [tianocore/edk2-pytool-extensions#104]
May have to have the script fetch the URL contents for backwards compat.

> WARNING: NU5125: The 'licenseUrl' element will be deprecated. Consider using the 'license' element instead.
> ------------------------------------------------
> --------------Cmd Output Finished---------------
> --------- Running Time (mm:ss): 00:05 ----------
> ------------------------------------------------
> =======================================
>  Name:        Mu-Basetools
>  ConfigFile:  D:\a\1\a/NugetPackageConfig.json
>  name:   Mu-Basetools
>  author_string:   ProjectMu, TianoCore
>  server_url:   https://api.nuget.org/v3/index.json
>  project_url:   https://aka.ms/projectmu
>  license_url:   https://github.com/tianocore/edk2/blob/master/License.txt
>  description_string:   Edk2 Basetools compiled for Windows and Linux; packaged for Project Mu
>  copyright_string:   Copyright 2018 - 2019

**Comment by Javagedes** [comment]
I've Created a PR to switch from using LicenseUrl to license.
