### ISSUE TITLE
GetPackagesPath should map paths to be workspace relative if they aren't already

### ISSUE THREAD

**Issue by matthewfcarlson** [tianocore/edk2-pytool-extensions#109]

**Comment by matthewfcarlson** [comment]
We should at least be checking to make sure the paths provided exist.

**Comment by spbrogan** [comment]
Can you provide a unit test showing it fails.  
PackagesPath should not be workspace relative.  They can be absolute.  

path_utilities.py in pytool library supports absolute path, workspace relative, or CWD relative.  invocables should be clear what the api expects but it should support packages path outside the workspace.

**Comment by spbrogan** [comment]
PackagesPath handling needs to be updated in all invocables to consistent. It should be in absolute path form so that both packages within the workspace can work as well as those external to the workspace.
