### ISSUE TITLE
Update might not work correctly

### ISSUE THREAD

**Issue by matthewfcarlson** [tianocore/edk2-pytool-extensions#111]
One of the keys features we advertise and rely on in stuart update is finding new dependencies if they are inside other dependencies. It looks like Bootstrap uses some global state to save the ENV state, so it won't search the workspace and find the new ext_deps.

Am I wrong here?

``` python
def BootstrapEnvironment(workspace, scopes=()):
    global ENVIRONMENT_BOOTSTRAP_COMPLETE, ENV_STATE

    if not ENVIRONMENT_BOOTSTRAP_COMPLETE:
        build_env = self_describing_environment(
            workspace, scopes).load_workspace()

```

**Comment by matthewfcarlson** [comment]
Added a test to make sure it works properly. It seems to work but I'm not sure how.

**Comment by spbrogan** [comment]
@corthon you know this?

**Comment by corthon** [comment]
edk2_update explicitly destroys the environment between retries.

https://github.com/tianocore/edk2-pytool-extensions/blob/5ad1bdef26cd5ad16e4718b4448f5858dba21a4c/edk2toolext/invocables/edk2_update.py#L110
