### ISSUE TITLE
stuart_ci_build skipped plugin/tests don't show up as skipped

### ISSUE THREAD

**Issue by spbrogan** [tianocore/edk2-pytool-extensions#13]
when plugin is skipped it is not recorded as skipped.  No indication that it even exists.  This is not desired behavior.

**Comment by matthewfcarlson** [comment]
https://github.com/tianocore/edk2-pytool-library/pull/10 this should fix it

**Comment by spbrogan** [comment]
there are other methods to skip plugin and they show up.  Use the config obj per package rather than globally.
