### ISSUE TITLE
XML log created by Stuart_ci_build has incorrect fields

### ISSUE THREAD

**Issue by spbrogan** [tianocore/edk2-pytool-extensions#14]
See python function instead of value. 

<testsuite id="0" name="PcAtChipsetPkg" package="Edk2CiBuild.<bound method CiBuildSettingsManager.GetGroupName of <CISettings.py.Settings object at 0x0000015B8EF25278>>.PcAtChipsetPkg" errors="0" tests="4" failures="0" skipped="0">

**Comment by spbrogan** [comment]
``` xml
<testsuite id="0" name="PcAtChipsetPkg" package="Edk2CiBuild.<bound method CiBuildSettingsManager.GetGroupName of <CISettings.py.Settings object at 0x0000015B8EF25278>>.PcAtChipsetPkg" errors="0" tests="4" failures="0" skipped="0">
```

**Comment by matthewfcarlson** [comment]
I think I know where this is

**Comment by matthewfcarlson** [comment]
#16 should fix this

**Comment by matthewfcarlson** [comment]
This wasn't quite fixed. We decided to remove GetGroupName
