### ISSUE TITLE
Expose Build_env from base_abstract_invokable to the settings class

### ISSUE THREAD

**Issue by matthewfcarlson** [tianocore/edk2-pytool-extensions#146]
**Is your feature request related to a problem? Please describe.**
There is a desire to iterate over the build_environment descriptors, which is currently not possible. We store them in build_env, which is just the SDE object. 

**Describe the solution you'd like**
There needs to be some way to get access to the information about what environmental descriptors have been applied. 

**Describe alternatives you've considered**
The version aggregator could be leveraged, but it is rather light in terms of information.

**Additional context**

**Comment by spbrogan** [comment]
Need more context.  For example what do you want to do?
