### ISSUE TITLE
Version Aggregator should not fail ext_deps of same name if they do not set flags.

### ISSUE THREAD

**Issue by matthewfcarlson** [tianocore/edk2-pytool-extensions#147]
**Is your feature request related to a problem? Please describe.**
When you have two ext_deps of the same name, different version, it fails. This is because we don't want to cause undefined behavior. This should only occur if they have flags like set build var.

**Describe the solution you'd like**
We should allow certain classes of ext_deps to exist together.

**Describe alternatives you've considered**

**Additional context**

**Comment by spbrogan** [comment]
why is this ok if they don't set the flags?  Please provide valid use case?

**Comment by matthewfcarlson** [comment]
Fixed by #220
