### ISSUE TITLE
Stuart_ci_build -p parameter eats all positional parameters following it

### ISSUE THREAD

**Issue by spbrogan** [tianocore/edk2-pytool-extensions#15]

**Comment by spbrogan** [comment]
something like this doesn't work:
>stuart_ci_build -c CISettings.py --Tool_Chain VS2017 -p PcAtChipsetPkg BLD_*_TOOLCHAIN=VS2017

the BLD_*_TOOLCHAIN is treated as part of -p

**Comment by matthewfcarlson** [comment]
So unfortunately, the python argparser doesn't have a great way to handle this. OptParser did but it's been deprecated. We have a few options:
- enforce the p parameter to always be last
- look at -p parameters and stuff them back into the remaining args if they aren't proper packages
- Switch to a non nargs and instead separate them oursevles (ie comma)
- Use a regex as the type for p (so each has to end in Pkg). This could potentially catch things like --IgnoreBadPkg for example but we could enforce a few rules

**Comment by matthewfcarlson** [comment]
Out of the options, I like 2 and 3 the best

**Comment by spbrogan** [comment]
I agree with number 2.  Csv is easy to handle with dev ops which is a bonus.
________________________________

**Comment by matthewfcarlson** [comment]
https://github.com/tianocore/edk2-pytool-extensions/pull/17

**Comment by kondalgithub** [comment]
Technically this is not a bug and  Its a known limitation in python argparser. 

Users can simply separate positional argument with "--".

stuart_ci_build -c CISettings.py --Tool_Chain VS2017 -p PcAtChipsetPkg -- BLD_*_TOOLCHAIN=VS2017

Agree with solution 2 but we might restrict the usage as  not all packages ends with Pkg.

**Comment by matthewfcarlson** [comment]
So I was a little confused by @spbrogan 's comment since he said 2 but then talked about CSV. So I implemented 3 but made it so we could switch to 2 or 4 pretty easily. 

I agree with @kondalgithub , this isn't technically a bug but rather an underlying implementation limitation. That said, I think fixing this issue would improve the user experience.

**Comment by kondalgithub** [comment]
I feel Option 3 is much better solution for long term, otherwise we may end up keep adding conditions inside the code.

**Comment by spbrogan** [comment]
I agree
