### ISSUE TITLE
Provide the download progress when retrieve external binary

### ISSUE THREAD

**Issue by changab** [tianocore/edk2-pytool-extensions#156]
Nicely shows the progress when retrieving external packages. The stuart_update looked like hangs if the download takes long. The download performance depends on the networking status for sure, my case is VM through proxy from the corporate network. ~ 1hr to download ARM GCC compiler.

**Comment by matthewfcarlson** [comment]
That's a rough download time. There's a nice caching mechanism so hopefully you only have to pay that penalty once. I agree- this would be a nice performance enhancement.
