### ISSUE TITLE
Allow env support object type of build variable

### ISSUE THREAD

**Issue by BobCF** [tianocore/edk2-pytool-extensions#174]
**Is your feature request related to a problem? Please describe.**
I think the active_buildvars in ShellEnvironment class can be used to share data between plugins or between plugins and the main process. Currently, the active_buildvars is a dict() and can only store str type of data.

I am trying to port Pytools to intel platform build. There is a configuration file used in the current intel platform build process. That configuration file needs to load at the beginning of a build process and its data need to be shared among multiple functions. The configuration file has a complex structure, so it's hard to convert its data into multiple simple strings.

**Describe the solution you'd like**
So can active_buildvars add object type support? like:
```
    def SetObject(self, k, v, comment, overridable=False):
        key = k.upper()
        self.Logger.debug("Trying to set key %s to value %s" % (k, v))
        self.ObjStore[key] = v
        return True

    def GetObject(self,k,default=None):
        if(k is None):
            logging.debug(
                "GetValue - Invalid Parameter key is None.")
            return None

        key = k.upper()
        en = self.ObjStore.get(key)
        if(en is not None):
            self.Logger.debug("Key %s found." % (key, ))
            return en
        return None
```

**Describe alternatives you've considered**

**Additional context**

**Comment by matthewfcarlson** [comment]
This is a good point and I agree, there should be some way for plugins to share data. Whether that's common inside pytools itself or implemented in the plugins that need to share information is a further discussion. BuildVars could be a way to pass information around but I feel like this is strapping on functionality it wasn't really designed to have. @spbrogan and @corthon?

**Comment by spbrogan** [comment]
@BobCF  - The buildvars have a lot of features wrapped into them.  For example you can set them from command line, config file, your platform py file, or the edk2 files being used (target.txt, tools_def.txt, dsc, fdf).   You can also export them for future use as an input config file.  There is also critical rules around setting them.  You can't change them after setting them.  This enables pytools to have various levels of default values and only the first set wins.  None of this would work for a nested object.  I would like more information about your use case before offering any ideas.   

Today the values are set very carefully and in a strict order.  Then after all values are set the operations run (prebuild, build, postbuild). This is why you don't really want your plugin's to change buildvars as this introduces complex ordering dependencies and a changing build environment.  Plugins run as part of pre/post build and thus can add things but shouldn't try to change anything.

Is there something in open platforms you can show to represent your issue or feel free to reach out using other channels to discuss other platforms.

**Comment by BobCF** [comment]
@spbrogan - Yes. I can see there are many good features on buildvars such as the setting if the var can be overridden and appending comments a var. I think they are very useful. And now I'm aware of your design that the build var should be set before running prebuild, build and postbuild. 

I am trying to port Pytools on the Intel platform. We have already had a set of python scripts to perform prebuild, build and postbuild. And we have a configuration file for platform build as well. All the scripts need to read the data in that configuration file,  some of them need to modify the configuration data. So we have a configuration data object, which can be read and write, shared among all scripts. For now, my idea of porting Pytool on Intel platform build is to convert the prebuild and postbuild scripts to Pytools plugins and share the configuration data object via Pytools buildvars.

The configuration file is .ini format. The configuration data structure is a dict, like conf[section][key] = value

The issue is not in open platforms. I'll see how to share the platform build scripts.

**Comment by spbrogan** [comment]
So not everything makes sense as a plugin.  
Plugins are meant to be reusable, generic or abstracted functionality.  Plugin's are also used for sharing with other projects/platforms. 

For platform specific steps for pre/post build these can be added to your "UefiBuilder" subclass object.  
https://github.com/tianocore/edk2-pytool-extensions/blob/c5259ee4997f72a00b0b1986c86ef5954eb897b2/edk2toolext/environment/uefi_build.py#L430

@out0xb2 did some work a while back to port some of the open kbl platforms.  You can see how he split plugins vs platformbuild based scripts / python code.  

https://github.com/out0xb2/edk2-platforms/tree/feature/py_platforms
and
https://github.com/out0xb2/edk2-platforms/blob/feature/py_platforms/Platform/Intel/KabylakeOpenBoardPkg/KabylakeRvp3/README-Pytools.md

**Comment by BobCF** [comment]
The kbl platform is a good example to learn how to use Pytools, but min-kbl is simpler than Intel real platforms.

There are many steps in pre/post builds and each step has actually been implemented as a library. Each platform has a python file "PlatformBIOSBuild.py" as the build entry point which is like the PlatformBuild.py in kbl platform example. Those libraries are re-usable for all platforms "PlatformBIOSBuild.py".

I want to refine those libraries to be Pytools plugins. Those plugins will be placed in Intel internal repo and shared for all Intel platforms. I think that aligns with your design for plugins.

**Comment by spbrogan** [comment]
@BobCF can this be closed for now.

**Comment by matthewfcarlson** [comment]
The plugins should all receive the builder object, so you could just add some sort of data passing methods that those plugins can rely on. Perhaps a class that your builders can all inherit from?

**Comment by BobCF** [comment]
Yes, the builder can be a media for the shareable variables cross plugins. I also want to make the platformbuild.py, which is under each platform package, to be as simple as possible. So I think I can try to create a class in the middle of UefiBuilder and PlatformBuilder, and store the sharable data in that new class.  If this way works, I think this issue can be closed. Thanks Matt and Sean.
