### ISSUE TITLE
Create a new variable for collecting environment information

### ISSUE THREAD

**Issue by BobCF** [tianocore/edk2-pytool-extensions#175]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I handle the workspace environment variable. The intel platform code base structure is like
```
root
   |___edk2
   |___intel
   |___edk2_platforms
```
The workspace is set to root/intel. Many existing settings are based on this workspace.

When I using Pytools, I have to set the workspace to root/ firstly since pytools collect the build environment under the workspace.  And after that, I need to set workspace back to root/intel.

**Describe the solution you'd like**
So I think whether pytools can use a new variable as the root of build environment?

**Describe alternatives you've considered**

**Additional context**

**Comment by matthewfcarlson** [comment]
This sort of breaks a fundamental assumption that's been made about the workspace. That layout is similar to what we use here for our platforms, the idea behind that all three of those would be submodules. I think this brings up a good question of whether the root workspace can move.

**Comment by spbrogan** [comment]
@BobCF  - What dependencies do you have on root/intel being the build root?  What changes would you have to make to move your root to root?  With packagespath i would think edk2 source would be easy to deal with.  What else do you have as far as assumptions.

**Comment by BobCF** [comment]
@spbrogan - Yes, the source path can be handled with packagespath. 

The Build folder and the Conf folder are bound to workspace. If I use root as workspace, I can't make the Build folder to be under root/intel. And the intel platform build scripts write/copy/delete other build output files under the workspace. I need to update those scripts to make those output files still under their original location.

**Comment by spbrogan** [comment]
For build output my suggestion would be instead of having a hardcoded path that makes your scripts fragile i would suggest using the build vars defined here. 
https://github.com/tianocore/edk2-pytool-extensions/blob/master/edk2toolext/environment/uefi_build.py#L397

As far as conf, pytools does have ability to change the source of the templates but not the output.  The output is always workspace/conf.  If you want info on template source let me know.

**Comment by BobCF** [comment]
OUTPUT_DIRECTORY is a macro in .dsc, so override it can only impact to building that dsc file. In a build process, there are multiple edk2 builds, such as building FSP from source and build BIOS. I think overriding OUTPUT_DIRECTORY can only impact one edk2 build.

I think there is another topic on how to handle multiple edk2 builds in one build process with Pytools.

**Comment by spbrogan** [comment]
So after looking at path utilities in pytool-library (https://github.com/tianocore/edk2-pytool-library/blob/master/edk2toollib/uefi/edk2/path_utilities.py#L35) i see that it supports packages_path in 3 forms.  Absolute path, relative path from workspace, finally relative path from CWD.  

Next we need to look thru the stuart side to see how packages path is setup, validated, and used.  If it can support packages_path outside the workspace.  

Finally we need to enable the SDE process to look thru not just the workspace but also the packages_path when then are not overlapping.  

@corthon - What do you think?

**Comment by spbrogan** [comment]
Looking at edk2_platform_build.py and edk2_ci_build.py there is a problem.   
example: 
https://github.com/tianocore/edk2-pytool-extensions/blob/master/edk2toolext/invocables/edk2_platform_build.py#L129

**Comment by spbrogan** [comment]
Changes is pr #193 will allow you to provide packages path in your settings file that are outside your workspace.  It allows packages path to be  workspace relative paths, absolute paths, or CWD relative paths (not recommended).  

I still don't think that is a good idea as I have no idea how you would setup the workspace reliably if it depended on code outside the workspace.   But that's a problem for you...and now the tools can support you.
