### ISSUE TITLE
Enable multiple threads to download ext_deps

### ISSUE THREAD

**Issue by BobCF** [tianocore/edk2-pytool-extensions#176]
**Is your feature request related to a problem? Please describe.**
There are many binary tools and binary files used in the Intel platform build. Currently, Pytool download ext_deps one by one.

**Describe the solution you'd like**
Enable multiple threads to download ext_deps can improve Pytools performance.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by matthewfcarlson** [comment]
I agree- this would be much faster. I'll check how feasible this would be.
