### ISSUE TITLE
Add progress indicator when Basetools doing Autogen

### ISSUE THREAD

**Issue by BobCF** [tianocore/edk2-pytool-extensions#178]
**Is your feature request related to a problem? Please describe.**
For the Intel platform build process, Autogen phase takes much time. Pytools hide the Basetools original "...." output. The progress indicator matters for the bios developer so I'd suggest adding the progress indicator support to Pytools.

**Describe the solution you'd like**
Print out the original "..." or some other progress indicator.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by matthewfcarlson** [comment]
So we currently just execute the build process as a new process and wait for it to complete. This would require us to watch the command output for the "..."

Though I have an idea I might look into to better pipe output from the build process to the console.

**Comment by Javagedes** [comment]
Closing this as it is over 3 years old. Please re-open if necessary. All build information is logged at INFO level. If so long as a platform has the logging level set to INFO or lower, the build information is displayed. If you are referring to --quiet mode for build.py, where only Build ... <object> is displayed (along with a few others), then that is something we could accommodate with a build flag if necessary.
