### ISSUE TITLE
internal path makes no sense

### ISSUE THREAD

**Issue by matthewfcarlson** [tianocore/edk2-pytool-extensions#179]
**Describe the bug**
Let's say I want to clone a zip file and extract a single file. I don't know how to do that. Set the compression type = zip and then internal path to what?

**To Reproduce**

**Expected behavior**

**Execution environment**
List the OS, python version, system environment variables, etc.

**Pip Packages**
If python related run `python -m pip list` and copy the output here

**Additional context**

**Comment by spbrogan** [comment]
does this not help? https://github.com/tianocore/edk2-pytool-extensions/blob/master/docs/usability/using_extdep.md#internal_path-required

**Comment by matthewfcarlson** [comment]
It helped some, but I was unable to get it to do what I wanted: extract the zip file and place the contents in the folder. This was when I was experimenting with jom. I'll probably create a PR to fix this when I get back around to it.

**Comment by spbrogan** [comment]
sounds like you want the root?  Can you try to add a unit test showing what you want and how it fails?

**Comment by matthewfcarlson** [comment]
Dup of #64
