### ISSUE TITLE
Edk2ToolsBuild.py throws exception with failed to build

### ISSUE THREAD

**Issue by matthewfcarlson** [tianocore/edk2-pytool-extensions#180]
**Describe the bug**
This is from issue #122 

```
Issues I am facing
c:\edk2\BaseTools>python Edk2ToolsBuild.py -t VS2019
SECTION - Init SDE
SECTION - Loading Plugins
SECTION - Start Invocable Tool
Traceback (most recent call last):
File "Edk2ToolsBuild.py", line 177, in
main()
File "Edk2ToolsBuild.py", line 173, in main
Edk2ToolsBuild().Invoke()
File "C:\Program Files\Python38\lib\site-packages\edk2toolext\base_abstract_invocable.py", line 141, in Invoke
retcode = self.Go()
File "Edk2ToolsBuild.py", line 139, in Go
raise Exception("Failed to build.")
Exception: Failed to build.
```

**To Reproduce**

**Expected behavior**

**Execution environment**
List the OS, python version, system environment variables, etc.

**Pip Packages**
If python related run `python -m pip list` and copy the output here

**Additional context**

**Comment by spbrogan** [comment]
this file is not in this repo.  Is the improvement needed in a base class from this repo or in the actual script found in edk2 repo?  Given that it inherits from BaseAbstractInvocable my guess is the Edk2ToolsBuild.py needs to be improved.

**Comment by matthewfcarlson** [comment]
Yeah- it looks like self.Go returns a non zero error code and it throws an exception. I'd have to look into where the error was being generated. I was just trying to separate two issues.
