### ISSUE TITLE
New version of flake8 added more checks and the repo is now failing

### ISSUE THREAD

**Issue by spbrogan** [tianocore/edk2-pytool-extensions#191]
**Describe the bug**
New version of flake8 added more checks and the repo is now failing.

./BasicDevTests.py:75:17: E741 ambiguous variable name 'l'
./edk2toolext/environment/conf_mgmt.py:85:17: E741 ambiguous variable name 'l'
./edk2toolext/capsule/signtool_signer.py:71:30: F541 f-string is missing placeholders
./edk2toolext/capsule/signtool_signer.py:98:26: F541 f-string is missing placeholders
./edk2toolext/capsule/pyopenssl_signer.py:42:26: F541 f-string is missing placeholders
./edk2toolext/bin/nuget.py:36:27: F541 f-string is missing placeholders

**To Reproduce**
1. pip install --upgrade flake8
2.  run flake8 on the entire repo

**Expected behavior**
A clean pass.

**Pip Packages**
 Using flake8-3.8.1-py2.py3-none-any.whl

**Comment by matthewfcarlson** [comment]
Fixed by #113
