### ISSUE TITLE
Exception: Failed to build

### ISSUE THREAD

**Issue by startergo** [tianocore/edk2-pytool-extensions#207]
```
C:\Windows\System32\edk2\BaseTools>python Edk2ToolsBuild.py -t VS2019
SECTION - Init SDE
SECTION - Loading Plugins
SECTION - Start Invocable Tool
Traceback (most recent call last):
  File "Edk2ToolsBuild.py", line 177, in <module>
    main()
  File "Edk2ToolsBuild.py", line 173, in main
    Edk2ToolsBuild().Invoke()
  File "C:\Python38\lib\site-packages\edk2toolext\base_abstract_invocable.py", line 141, in Invoke
    retcode = self.Go()
  File "Edk2ToolsBuild.py", line 139, in Go
    raise Exception("Failed to build.")
Exception: Failed to build.
```

**Comment by spbrogan** [comment]
Please see issue #180 
The error message is unclear but in short it isn't really a pytool bug.  

To help you resolve your issue there is supposed to be a readme in edk2 but i can't seem to find it.  I would guess you have not run `git submodule update --init --recursive`   

Now that the edk2 basetools is using submodules it is required to be run before building the basetools.

**Comment by spbrogan** [comment]
If you believe that this is till an issue with pytool, please collect the basetools build log for more info about what is happening.  

I put together a readme that has complete steps about how I build ovmf or other platforms within edk2.  This is also how the automated ci does it. 
https://github.com/tianocore/edk2/blob/master/OvmfPkg/PlatformCI/ReadMe.md

Hope that helps.

**Comment by startergo** [comment]
> 
> 
> Please see issue #180
> The error message is unclear but in short it isn't really a pytool bug.
> 
> To help you resolve your issue there is supposed to be a readme in edk2 but i can't seem to find it. I would guess you have not run `git submodule update --init --recursive`
> 
> Now that the edk2 basetools is using submodules it is required to be run before building the basetools.

This fixed it thanks. It would be a good idea to add it to the readme.

**Comment by spbrogan** [comment]
thanks.

**Comment by Sunxingzhezhexingsun** [comment]
> Please see issue #180 The error message is unclear but in short it isn't really a pytool bug.
> 
> To help you resolve your issue there is supposed to be a readme in edk2 but i can't seem to find it. I would guess you have not run `git submodule update --init --recursive`
> 
> Now that the edk2 basetools is using submodules it is required to be run before building the basetools.

I met the same error：
```
(venv_edk2) D:\Work\UEFI Security\UEFIWorkspace\edk2>python BaseTools/Edk2ToolsBuild.py -t VS2019
SECTION - Init SDE
SECTION - Loading Plugins
SECTION - Start Invocable Tool
Traceback (most recent call last):
  File "BaseTools/Edk2ToolsBuild.py", line 177, in <module>
    main()
  File "BaseTools/Edk2ToolsBuild.py", line 173, in main
    Edk2ToolsBuild().Invoke()
  File "D:\Work\UEFI Security\UEFIWorkspace\edk2\venv_edk2\lib\site-packages\edk2toolext\base_abstract_invocable.py", line 146, in Invoke
    retcode = self.Go()
  File "BaseTools/Edk2ToolsBuild.py", line 139, in Go
    raise Exception("Failed to build.")
Exception: Failed to build.
```

And, I followed all the steps in this manual：https://github.com/tianocore/edk2/blob/master/OvmfPkg/PlatformCI/ReadMe.md
and,  `git submodule update --init --recursive` not work.
