### ISSUE TITLE
NugetDependency._fetch_from_cache() is no longer working

### ISSUE THREAD

**Issue by corthon** [tianocore/edk2-pytool-extensions#228]
https://github.com/tianocore/edk2-pytool-extensions/blob/37d367816349270e4842864cd8883efdadea682e/edk2toolext/environment/extdeptypes/nuget_dependency.py#L126

Suspect that Nuget has changed its cache store and the extra 'package_name' can be dropped from the end.

**Comment by matthewfcarlson** [comment]
Excellent. Good diagnosis.

What's the impact? Is this linux only or windows? Does this affect the usage of the system?

**Comment by corthon** [comment]
I noticed it on Windows. Checking Linux...

**Comment by corthon** [comment]
Hmmm... suggested fix might be incorrect. I've got one cached package called "content" and another with package_name (as the final directory name).

**Comment by corthon** [comment]
It *may* be that we can just assume whatever directory under that version directory is the content.

**Comment by corthon** [comment]
Hmmm... this is an odd assortment. I wonder how they published this one that has an inner "content" directory.

**Comment by corthon** [comment]
Okay, so here's a proposed fix. This won't do bad things if the inner cache doesn't look right, but it will at least let the caller know that there's a cache that isn't being used.

```patch
diff --git a/edk2toolext/environment/extdeptypes/nuget_dependency.py b/edk2toolext/environment/extdeptypes/nuget_dependency.py
index dd34d0c..3c797ea 100644
--- a/edk2toolext/environment/extdeptypes/nuget_dependency.py
+++ b/edk2toolext/environment/extdeptypes/nuget_dependency.py
@@ -122,14 +122,22 @@ def _fetch_from_cache(self, package_name):
         #
         # Now, try to locate our actual cache path
         nuget_version = NugetDependency.normalize_version(self.version)
+
         cache_search_path = os.path.join(
-            self.global_cache_path, package_name.lower(), nuget_version, package_name)
+            self.global_cache_path, package_name.lower(), nuget_version)
+        inner_cache_search_path = os.path.join(cache_search_path, package_name)
         if os.path.isdir(cache_search_path):
-            logging.info(
-                "Local Cache found for Nuget package '%s'. Skipping fetch.", package_name)
-            shutil.copytree(cache_search_path, self.contents_dir)
-            self.update_state_file()
-            result = True
+            # If we found a cache for this version, let's use it.
+            if os.path.isdir(inner_cache_search_path):
+                logging.info(
+                    "Local Cache found for Nuget package '%s'. Skipping fetch.", package_name)
+                shutil.copytree(inner_cache_search_path, self.contents_dir)
+                self.update_state_file()
+                result = True
+            # If this cache doesn't match our heuristic, let's warn the user.
+            else:
+                logging.warning(
+                    "Local Cache found for Nuget package '%s', but could not find contents. Malformed?", package_name)
 
         return result
 

```

**Comment by corthon** [comment]
The other proposal I would make is that we can scandir the outer path and assume that if there's exactly 1 inner dir, that's the package. The we throw a warning if there is 0 or >2 inner dirs.

I've looked at a few dozen caches, and several versions of each, and only found a couple that would fail this test.

**Comment by corthon** [comment]
For future reference (if we go scandir)...
https://stackoverflow.com/questions/800197/how-to-get-all-of-the-immediate-subdirectories-in-python

**Comment by spbrogan** [comment]
can this be closed given that a change was merged?
