### ISSUE TITLE
Repo resolver support shorthand commits

### ISSUE THREAD

**Issue by matthewfcarlson** [tianocore/edk2-pytool-extensions#236]
**Describe the bug**
The edk2toolext\environment\repo_resolver.py doesn’t accept shorthand commit values.  To ensure the dependency file has a correct commit hash value, I suggest adding a check for a full commit hash value near line 215:

        else:
            if len(commit) != 40:
                logger.critical(
                    "Dependency {0} has a malformed commit hash.  Fail.".format(dep["Path"]))
                raise Exception(
                    "Dependency {0} has a malformed commit hash.  Fail.".format(dep["Path"]))
            if repo.head.commit == commit:

**To Reproduce**

**Expected behavior**

**Execution environment**
List the OS, python version, system environment variables, etc.

**Pip Packages**
If python related run `python -m pip list` and copy the output here

**Additional context**

**Comment by Javagedes** [comment]
Short commit id support has been added via #371 to both repo_resolver and git_dependency to resolve this issue.
