### ISSUE TITLE
Omnicache does not handle remote tags to avoid collisions.

### ISSUE THREAD

**Issue by joschock** [tianocore/edk2-pytool-extensions#250]
**Describe the bug**
If you add two remotes to Omnicache, and both have the same tag name, and you instruct omnicache to fetch the tags, fetch of the second one will fail with something like the following:

INFO - Cmd to run is: git fetch libdivsufsort --tags
INFO - ------------------------------------------------
INFO - --------------Cmd Output Starting---------------
INFO - ------------------------------------------------
INFO - From https://github.com/y-256/libdivsufsort
INFO -  ! [rejected]                1.2.3      -> 1.2.3  (would clobber existing tag)
INFO -  ! [rejected]                2.0.1      -> 2.0.1  (would clobber existing tag)

**To Reproduce**
1. Initialize an omnicache instance that caches two different projects that use the same tag name conventions. Try:
https://github.com/pyca/cryptography/tags
and
https://github.com/y-256/libdivsufsort.git
2. Note a failure will be reported similar to above during the fetch.

**Expected behavior**
Since what we actually care about for Omnicache is the _objects_, not the tags themselves, we need a mechanism where by the reachable objects from those tags are in the omnicache, even if the tag names are duplicates. Consequently, we'll probably need to fiddle with the remote refspec so that the tags are fetched into different local per-remote namespaces. 

**Execution environment**
Not applicable; if you can run omnicache, you can reproduce above. 

**Pip Packages**
Package                Version
---------------------- ---------
antlr4-python3-runtime 4.7.1
cffi                   1.14.3
cryptography           3.3.1
edk2-pytool-extensions 0.14.1
edk2-pytool-library    0.10.13
future                 0.18.2
git-filter-repo        2.29.0
pefile                 2019.4.18
pip                    21.0.1
pycparser              2.20
PyYAML                 5.3.1
setuptools             49.2.1
six                    1.15.0

**Additional context**

**Comment by spbrogan** [comment]
@joschock  - This is fixed now.  I noticed some omnicache changes you submitted that looked like it was handling tags differently than before.

**Comment by joschock** [comment]
Yep, this is fixed. Can close with latest omnicache.
