### ISSUE TITLE
Omnicache does not honor configuration change with respect to tags setting

### ISSUE THREAD

**Issue by joschock** [tianocore/edk2-pytool-extensions#251]
**Describe the bug**
If you initialize a new remote for omnicache with the tag setting; and then later pass a new version of the config file with a different tag setting, omnicache retains the original tag setting unless you remove the remote explicitly and re-add it.

**To Reproduce**
1. Create an omnicache foo.yaml configuration file with the following:
```yaml
- name: libdivsufsort
  url: https://github.com/y-256/libdivsufsort.git
  tag: true
```
2. initialize an omnicache with it: omnicache.exe --init -c foo.yaml c:\temp\cache
3. observe that libdivsufsort is fetched with tags.
4. remove the `tag: true` from foo.yaml
4. re-initialize the omnicache with the new foo.yaml
5. observe that libdvsufsort is again fetched with tags, despite having the tag field removed from config.

**Expected behavior**
Second fetch should honor the new configuration and not fetch tags. 

**Execution environment**
Not applicable - should be reproducible in any environment where omnicache can run.

**Pip Packages**
Package                Version
---------------------- ---------
antlr4-python3-runtime 4.7.1
cffi                   1.14.3
cryptography           3.3.1
edk2-pytool-extensions 0.14.1
edk2-pytool-library    0.10.13
future                 0.18.2
git-filter-repo        2.29.0
pefile                 2019.4.18
pip                    21.0.1
pycparser              2.20
PyYAML                 5.3.1
setuptools             49.2.1
six                    1.15.0

**Additional context**

**Comment by Javagedes** [comment]
Talked offline with @joschock this issue was handled via #252, however it was not closed.
