### ISSUE TITLE
Stuart fails to find NuGet.exe on PATH

### ISSUE THREAD

**Issue by brandonaut** [tianocore/edk2-pytool-extensions#259]
**Describe the bug**
Stuart fails to find NuGet.exe from my PATH.

**To Reproduce**
1. Verify that NuGet.exe is available in PATH
2. Remove edk2toolext\bin\nuget.exe from .venv, to force stuart to look in the PATH
2. Run `stuart_update`
3. See error: `We weren't able to find Nuget! Please reinstall your pip environment`

**Expected behavior**
NuGet.exe is discovered on my PATH and stuart_update downloads the necessary packages for the SDE.

**Execution environment**
Windows 10 20H2
Python 3.8.6

**Pip Packages**
```
$ python -m pip list
Package                Version              Location
---------------------- -------------------- --------------------------------------
antlr4-python3-runtime 4.9.2
cached-property        1.5.2
certifi                2020.12.5
chardet                4.0.0
classproperties        0.1.3
colorama               0.4.4
datafiles              0.11.1
edk2-pytool-extensions 0.14.3.dev2+g9400bfd c:\fw\tianocore\edk2-pytool-extensions
edk2-pytool-library    0.10.13
future                 0.18.2
gitdb                  4.0.5
gitman                 2.2
GitPython              3.1.14
idna                   2.10
invoke                 1.5.0
Jinja2                 2.11.3
loguru                 0.5.3
MarkupSafe             1.1.1
minilog                2.0
parse                  1.18.0
pefile                 2021.5.24
pip                    20.2.4
PyYAML                 5.4.1
requests               2.25.1
ruamel.yaml            0.16.12
ruamel.yaml.clib       0.2.2
setuptools             50.3.2
smmap                  3.0.5
tomlkit                0.5.11
typing-extensions      3.7.4.3
untangle               1.1.1
urllib3                1.26.3
wheel                  0.35.1
win32-setctime         1.0.3
```
**Additional context**
This seems to be caused by the quote wrapping here: https://github.com/tianocore/edk2-pytool-extensions/blob/9400bfd0162a0da40f14f7f7154ac6097de43302/edk2toolext/environment/extdeptypes/nuget_dependency.py#L49

`os.path.isfile(nuget_path)` returns `False` if `nuget_path` is wrapped in quotes.

**Comment by spbrogan** [comment]
Before making the change i was thinking about your scenario a little more.  If you want to use a custom/different version of nuget.exe would you rather. 

1. Look for env variable NUGET_PATH and use that if defined.  Otherwise fall back to nuget published in package. 

or 

2. Look for Nuget.exe on the path and use that if defined.  Otherwise fall back to nuget.exe published in package.  

or 

3. Use Nuget.exe published.  If not found look for it on the path.    <current behavior but doesn't seem optimal>

**Comment by brandonaut** [comment]
I think it's best to prefer the nuget that's published in the repo (the 3rd option), in order to make the build environment as reproducible as possible. 

A little more info on how I encountered this issue:
In my case, my goal wasn't actually to use a custom version of NuGet. I was just installing edk2-pytool-extensions in develop mode (using poetry). Since it wasn't packaged, the `edk2toolext\bin` folder didn't exist. This caused it to fall back to looking in the PATH for nuget.exe, which failed due to the quotes. 

Perhaps that hardcoded path needs to be fixed as well, so that develop mode can be used?

**Comment by spbrogan** [comment]
can you help me understand develop mode.  Isn't that the same as `pip install -e <path to edk2-pytool-extensions root>` ?  Whenever i do this it downloads NuGet.exe when installing.

**Comment by spbrogan** [comment]
i implemented option 1 above as it does give users a defined way to override the nuget version without having the delete nuget.exe in the package.   I agree that for consistency this shouldn't be used but the version aggregator can be used to log the version of nuget.exe and nuget_path.

**Comment by brandonaut** [comment]
I was referring specifically to a [Poetry path dependency with the develop attribute](https://python-poetry.org/docs/dependency-specification/#path-dependencies), but I believe it's equivalent to `pip install -e`. In any case, I just tried installing it with develop mode and NuGet.exe was pulled down just fine. I must've done something weird to get in that state before. Ignore my comments about the hard-coded path :)

Option 1 is fine, especially if the version of nuget.exe is recorded somewhere for diagnostics.
