### ISSUE TITLE
Git external dependencies do not include the repo root in published path

### ISSUE THREAD

**Issue by cfernald** [tianocore/edk2-pytool-extensions#287]
**Describe the bug**
When consuming a git based external dependency the published path points to the ext_dep directory, but to consume the git repository in a useful way the repository root directory is needed. This is problematic for attempting to consume a git repository that contains EDKII packages as they cannot be resolved referencing the build variable without manually appending the assumed repository root directory name.

**To Reproduce**
1. Create a git external dependency. e.g.
2. Use "set_build_var" flag.
3. Reference build variable to include in packages path

**Expected behavior**
The build script can resolve packages in the git external dependency. Currently, the repo path needs to be manually added to the path in the scripts to resolve packages.

**Execution environment**
N/A

**Pip Packages**
N/A

**Additional context**
N/A

**Comment by spbrogan** [comment]
merged
