### ISSUE TITLE
stuart_ci_build should  not put all dependency in the PackagesPath

### ISSUE THREAD

**Issue by spbrogan** [tianocore/edk2-pytool-extensions#31]

**Comment by matthewfcarlson** [comment]
@spbrogan what's the reasoning? Is there an issue in a build

**Comment by spbrogan** [comment]
for an example look at edk2.   These dependencies are not aligned with packages path.  
https://github.com/spbrogan/edk2-staging/blob/edk2-stuart-ci-latest/CISettings.py#L53
