### ISSUE TITLE
Pin development dependencies for more consistent dev process

### ISSUE THREAD

**Issue by spbrogan** [tianocore/edk2-pytool-extensions#311]
**Is your feature request related to a problem? Please describe.**
Pin all external dependencies other than our integration tests.
Enable dependabot to generate PRs for updates automatically

**Describe the solution you'd like**
see above

**Describe alternatives you've considered**
let the dependencies float with latest.  This has been tried but leads to instability

**Additional context**
None

**Comment by Javagedes** [comment]
#312
