### ISSUE TITLE
Unit test instruction is not working in WSL(ubuntu20.04)

### ISSUE THREAD

**Issue by TedKrChen** [tianocore/edk2-pytool-extensions#313]
**Describe the bug**
The last command from UnitTestFramework instruction, the following command will always fail.
>stuart_ci_build -c ./.pytool/CISettings.py TOOL_CHAIN_TAG=VS2019 -t NOOPT  BLD_*_UNIT_TESTING_DEBUG=TRUE

And the parameter ```BLD_*_UNIT_TESTING_DEBUG=TRUE``` is not working too, cannot find any debug message.
**To Reproduce**
1. stuart_ci_build -c ./.pytool/CISettings.py TOOL_CHAIN_TAG=VS2019 -t NOOPT  BLD_*_UNIT_TESTING_DEBUG=TRUE
2. errors like:
``` 
SECTION - Init SDE
WARNING - Using Pip Tools based BaseTools
SECTION - Loading Plugins
SECTION - Start Invocable Tool
SECTION - Getting Environment
SECTION - Loading plugins
SECTION - Building MdePkg Package
PROGRESS - --Running MdePkg: Host Unit Test Compiler Plugin NOOPT --
WARNING - Allowing Override for key TARGET_ARCH
PROGRESS - Start time: 2022-09-05 14:42:28.098579
PROGRESS - Setting up the Environment
PROGRESS - Running Pre Build
PROGRESS - Running Build NOOPT
CRITICAL - Build failed
PROGRESS - End time: 2022-09-05 14:42:29.325620  Total time Elapsed: 0:00:01
ERROR - --->Test Failed: Host Unit Test Compiler Plugin NOOPT returned 1
ERROR - Overall Build Status: Error
PROGRESS - There were 1 failures out of 1 attempts
SECTION - Summary
ERROR - Error
```
**Expected behavior**
N/A

**Execution environment**
Ubuntu 20.04 (wsl)

**Pip Packages**
edk2-pytool-library==0.11.2
edk2-pytool-extensions~=0.16.0
edk2-basetools==0.1.24
antlr4-python3-runtime==4.7.1

**Comment by Javagedes** [comment]
It looks like you are attempting to build in Ubuntu 20.04 with the VS2019 tool chain. The supported tool chain for Ubuntu 20.04 is GCC5. 

Please attempt to build either with Windows+VS2019 or Ubuntu+GCC5 and let me know if the error persists.

**Comment by TedKrChen** [comment]
Thank you , I had change  tool chain to GCC5 , it work now
