### ISSUE TITLE
[Feature]: Clarify the supported versions of python and add tests for each

### ISSUE THREAD

**Issue by makubacki** [tianocore/edk2-pytool-extensions#345]
### What does the feature solve?

In this project it is not clear what versions of python are required, supported, and tested against. This makes it harder for consumers of this project to know their requirements are. It also makes it harder for the developers of this project as they don't know what language features they are allowed to use.

### Describe the solution

1. Add documentation for the supported versions of python and the rationale and process.
2. Update documentation, Pypi metadata to be accurate.
3. Add PR gate tests for the supported versions of python
4. Add CI gates and status badges for each supported version

### Additional context

Note: This is a copy of the feature request https://github.com/tianocore/edk2-pytool-library/issues/201 from the edk2-pytool-library to track similar work in this repo (edk2-pytool-extensions).

_As pytools usage expands it is critical to communicate these things as well as provide roadmap to indicate how these change as python releases new versions._

**Comment by Javagedes** [comment]
Discussion here:

https://github.com/tianocore/edk2-pytool-library/issues/201

**Comment by Javagedes** [comment]
Per @kondalgithub's suggestion in #354, we will specify the supported versions in the pypi package by adding `python_requires='>=3.9'` to setup.py
