### ISSUE TITLE
[Bug]: edk2-pytool-extentions package does not declare  supported Python versions

### ISSUE THREAD

**Issue by kondalgithub** [tianocore/edk2-pytool-extensions#354]
### Contact Details

kondal.r.purma@intel.com

### Describe the Bug

edk2-pytool-extentions not declared Python version required to install the package. 
Users might successfully installs the package in any Python 3.x versions and expect to work.

### What Python version are you using?

Python 3.8

### Reproduction steps

1.Install Python 3.8
2.Install edk2-pytool-extentions
3.stuart_ci_build command to build/run unit tests

### Expected behavior

Package should works as expected in any version of Python ,as we dont declare (min or all )supported Python versions.

### Additional context

https://peps.python.org/pep-0440/

In setup along with classifier add the "python_requires" will fix the issue.
Ex:
Add 
 python_requires='>=3.9',
To setup.py (as we are not using pyproject.toml for package maintenance) .

**Comment by Javagedes** [comment]
@kondalgithub Thank you for reporting this bug! 

We currently have a similar issue open for this situation. Please see: #345. We currently support the last 3 minor versions of python (Currently: 3.9, 3.10, 3.11). I'm in the process of updating our CI pipelines to run our tests on all three versions of python as seen in #353 and should have it done in the next couple of days. I will update #345 to ensure we also include `python_requires='>=3.9'`. 

Thank you again!
