### ISSUE TITLE
[Feature]:  edk2-pytool-extensions  requires a CI test to validate the package against all  Python versions supported

### ISSUE THREAD

**Issue by kondalgithub** [tianocore/edk2-pytool-extensions#366]
### What does the feature solve?

This feature helps to validate the package against all Python versions supported and works as expected.
Without this check its possible that a given release might work with 3.x and breaks with 3.y.

### Describe the solution

Add CI support to validate package against all supported Python versions.

**Comment by Javagedes** [comment]
@kondalgithub 

We recently updated our ci, unit tests, and integration tests to do exactly this. Here is an example of the tests in a recently merged PR: https://github.com/tianocore/edk2-pytool-extensions/pull/364/checks

Please let me know if there are any other tests not covered that you are concerned about.

As it stands this is what is tested:

**CI (Via github action) on Python 3.11:**
flake8
markdownlint
cspell
pydocstyle
mkdocs
basicdevtests (Custom script)

**Unit Tests (Via github action):**
(ubuntu-latest, python 3.9)
(ubuntu-latest, python 3.10)
(ubuntu-latest, python 3.11)
(windows-latest, python 3.9)
(windows-latest, python 3.10)
(windows-latest, python 3.11)

**Integration Tests (Via Azure Pipelines):**
(edk2, windows-2019, python 3.9)
(edk2, windows-2019, python 3.10)
(edk2, windows-2019, python 3.11)
(edk2, ubuntu-20.04, python 3.9)
(edk2, ubuntu-20.04, python 3.10)
(edk2, ubuntu-20.04, python 3.11)
(ProjectMu, windows-2022, python 3.9)
(ProjectMu, windows-2022, python 3.10)
(ProjectMu, windows-2022, python 3.11)
(ProjectMu, ubuntu-22.04, python 3.9)
(ProjectMu, ubuntu-22.04, python 3.10)
(ProjectMu, ubuntu-22.04, python 3.11)

**Comment by Javagedes** [comment]
@kondalgithub I'm going to go ahead and close this because I think the CI we currently have meets your intent, however please reopen and let me know if you have any concerns or want more CI.
