### ISSUE TITLE
ci_setup doesn't check to make sure dependencies are up to date

### ISSUE THREAD

**Issue by matthewfcarlson** [tianocore/edk2-pytool-extensions#37]
It just checks to make sure that they're on the right branch. Maybe commit only? Similar to gitsubmodules?

**Comment by Javagedes** [comment]
To be more descriptive, within the Checkout method, it will perform no checkout if we are on the correct branch. The concern here is that even though we are on the correct branch, we may not be on the latest.

My suggestion is that we do a repo.pull() around L117, as this is the only logic flow that isn't being freshly cloned, so could have the possibility of having the correct branch, but out of date branch.

**Comment by Javagedes** [comment]
Resolving this as not an issue. stuart_ci_setup / stuart_setup are commands to bootstrap the environment directly after a clone and should really only be used once. It is not a replacement for git operations. We expect that a developer be responsible for updating submodules and git repos manually. 

HOWEVER, stuart_ci_setup will checkout the top of the branch in a detached head state if you fully define the branch (i.e. origin\branchname), which means the git dependency will be properly updated if stuart_ci_setup is called multiple times. Please note that this is NOT true when just providing the branch name (i.e. branchame). In that situation, it will only verify the branch is correct.

There are two ways to specify a branch dependency:
1. Only the branchname i.e. branchname. In this situation, you are correct, if it is on the correct branch, the git checkout will not update an out-of-date branch.
2. A Fully defined branch i.e. origin\branchname. In this situation, it checks out the top of the branch in a detached head state, which means the dependency will be up to date.
