### ISSUE TITLE
[Bug]: stuart_update doesn't work on macOS or FreeBSD

### ISSUE THREAD

**Issue by bcran** [tianocore/edk2-pytool-extensions#390]
### Contact Details

rebecca@bsdio.com

### Describe the Bug

stuart_update tries to run NuGet.exe, which is a .NET assembly. While Linux supports misc binary formats and so can execute it directly, macOS and FreeBSD don't and so get a permission denied error.

A simple fix would be to run it as "mono NuGet.exe" on such systems.

### What Python version are you using?

Python 3.9

### Reproduction steps

1. stuart_setup -c .pytool/CISettings.py
2. stuart_update -c .pytool/CISettings.py TOOL_CHAIN_TAG=GCC5

### Expected behavior

Dependencies should be fetched and extracted.

### Execution Environment

macOS or FreeBSD

**Comment by spbrogan** [comment]
This is more of an enhancement as these tools have never claimed to support MacOS or FreeBSD.  @bcran I look forward to your help getting these operating systems added to the supported list.

**Comment by Javagedes** [comment]
Hi @bcran I've created a branch that adds mono when the os is MacOS or FreeBSD, which we already do with Linux. I was able to find online that a mac system returns Darwin for the command we use, but I was not able to find anything for a FreeBSD system.

Unfortunately, I don't have a Mac or Free BSD to verify, so could you please run the following python script and let me know the results, so I can update accordingly?
Would you please run the following script on your Mac and FreeBSD systems and let me know the results, so I can update the 

```python
import platform
print(platform.uname().system)
```

**Comment by bcran** [comment]
> Hi @bcran I've created a branch that adds mono when the os is MacOS or FreeBSD, which we already do with Linux. I was able to find online that a mac system returns Darwin for the command we use, but I was not able to find anything for a FreeBSD system.
```
Could we instead add mono on anything that _isn't_ Windows? That should let it work on OpenBSD, NetBSD, Solaris, etc. without further changes.

**Comment by Javagedes** [comment]
Yes that should be fine. I'll update the branch. Can you please verify it works on your system? You can do so by cloning the repo, switching to the branch, and running `pip install --upgrade -e .` at the base of the repo while in your virtual environment for your platform repo (if you use a virtual environment). You can verify you successfully updated by running `pip list`, and checking that you are on a dev branch for edk2-pytool extensions.

![image](https://user-images.githubusercontent.com/24388509/211599897-b1b1bc6e-b8ac-4de5-acc7-3e667f037693.png)

From there you can re-run stuart_update and verify if it works.

**Comment by Javagedes** [comment]
@bcran I forgot to mention you so you get notified, so I'm doing it now :)

**Comment by bcran** [comment]
Thanks. Please let me know the name of the branch when it's ready!

**Comment by Javagedes** [comment]
@bcran The branch is https://github.com/Javagedes/edk2-pytool-extensions/tree/nuget-os-enhance or you can clone https://github.com/tianocore/edk2-pytool-extensions and checkout PR #391

**Comment by bcran** [comment]
Thanks! That's solved this problem. I now get further, and these messages are clearly for a separate bug issue.
```
(.venv) bcran@procan edk2 % stuart_update -c .pytool/CISettings.py TOOL_CHAIN_TAG=XCODE5
SECTION - Init SDE
WARNING - Using Pip Tools based BaseTools
ERROR - Could not find appropriate folder for mu-uncrustify-release. Host(os='Darwin', arch='x86', bit='64')
ERROR - Could not find appropriate folder for mu_nasm. Host(os='Darwin', arch='x86', bit='64')
ERROR - Could not find appropriate folder for edk2-acpica-iasl. Host(os='Darwin', arch='x86', bit='64')
ERROR - Could not find appropriate folder for mu-uncrustify-release. Host(os='Darwin', arch='x86', bit='64')
ERROR - Could not find appropriate folder for mu_nasm. Host(os='Darwin', arch='x86', bit='64')
ERROR - Could not find appropriate folder for edk2-acpica-iasl. Host(os='Darwin', arch='x86', bit='64')
SECTION - Loading Plugins
SECTION - Start Invocable Tool
SECTION - Initial update of environment
ERROR - Could not find appropriate folder for mu-uncrustify-release. Host(os='Darwin', arch='x86', bit='64')
ERROR - Could not find appropriate folder for mu_nasm. Host(os='Darwin', arch='x86', bit='64')
ERROR - Could not find appropriate folder for edk2-acpica-iasl. Host(os='Darwin', arch='x86', bit='64')
Updating. Done
SECTION - 	Updated/Verified 3 dependencies
SECTION - Second pass update of environment
ERROR - Could not find appropriate folder for mu-uncrustify-release. Host(os='Darwin', arch='x86', bit='64')
ERROR - Could not find appropriate folder for mu_nasm. Host(os='Darwin', arch='x86', bit='64')
ERROR - Could not find appropriate folder for edk2-acpica-iasl. Host(os='Darwin', arch='x86', bit='64')
ERROR - Could not find appropriate folder for mu-uncrustify-release. Host(os='Darwin', arch='x86', bit='64')
ERROR - Could not find appropriate folder for mu_nasm. Host(os='Darwin', arch='x86', bit='64')
ERROR - Could not find appropriate folder for edk2-acpica-iasl. Host(os='Darwin', arch='x86', bit='64')
ERROR - Could not find appropriate folder for mu-uncrustify-release. Host(os='Darwin', arch='x86', bit='64')
ERROR - Could not find appropriate folder for mu_nasm. Host(os='Darwin', arch='x86', bit='64')
ERROR - Could not find appropriate folder for edk2-acpica-iasl. Host(os='Darwin', arch='x86', bit='64')
Updating. Done
SECTION - 	Updated/Verified 3 dependencies
SECTION - Summary
PROGRESS - Success
```

**Comment by Javagedes** [comment]
Closing in favor of #399
