### ISSUE TITLE
[Feature]: Simple way to bypass ext_deps / avoid tool downloads

### ISSUE THREAD

**Issue by osteffenrh** [tianocore/edk2-pytool-extensions#416]
### What does the feature solve?

In some cases I want to be able to run stuart and use
the tools (gcc, nasm, iasl, ...) from my local system,
instead of downloading them.

This can be beneficial:

- when running without network access or bad network connection
  that causes downloads to fail (especially problematic in CI). 
- Or when the tools are provided by a container environment.
- For testing with other versions of the compiler, etc.
 

### Describe the solution

A command line flag (or similar) could be added to skip all downloads.
Then all tools are expected to be available in the PATH, or indicated
by other environment variables (for example `GCC5_*_PREFIX`)

### Have you considered any alternatives?

Deleting the ext_dep files has the desired effect.

### Additional context

This would be useful for the EDK2 CI on Linux, where a container environment
is used to provide the tools (avoiding downloads from multiple places at CI
run time).

**Comment by Javagedes** [comment]
Should not be difficult. Just don't run stuart_update and I could add an `--offline` flag to stuart_build. I will look into what is needed to be done to search for local tools if --offline is set.

**Comment by osteffenrh** [comment]
There was a discussion about this: https://github.com/tianocore/edk2-pytool-extensions/discussions/323

**Comment by Javagedes** [comment]
Will review. Thanks.

**Comment by Javagedes** [comment]
@osteffenrh Realistically, no changes are needed on edk2-pytool-extensions itself. There are just a few things that need to be done in the repo to enable this. We will use MU_BASECORE's .pytool/CISettings.py file. 

The below is just an example of a way that will work. Adjust to your needs.
1. change nasm's scope to `edk2-build-online` (Only providing example for nasm but you'll need adjust others)
2. In `Settings.AddCommandLineOptions()` add a new argument for --offline
3. In `Settings.RetrieveCommandLineOptions()` set self.offline = args.offline
4. In `Settings.GetActiveScopes()` add `edk2-build-online` to the default list of scopes
5. In `Settings.GetActiveScopes()` add a check for self.offline and if it's true, remove the edk2-build-online (Or vice-versa via adding `edk2-build-online` to the list of scopes if self.offline is false)

And that's it! At this point, even if the dependencies are downloaded, a `stuart_ci_build -c .pytool/CISettings.py --offline`, it will not use those dependencies. You could even skip `stuart_update` all together if you wanted as all it does is download external dependencies.

**Comment by Javagedes** [comment]
@osteffenrh Please feel free to re-open this if you have any issues doing what I mentioned above! Or reach out directly. I'm here to help, only closing as it does not require any changes to edk2-pytool-extensions itself.

**Comment by osteffenrh** [comment]
Thanks, @Javagedes.  I'll give it a try.

At least for the EDK2 CI, I'd skip `sturat_update` then.
I want to avoid that the CI can fail if external files can't be
downloaded for some reason.
