### ISSUE TITLE
[Feature]: A utility to audit a systems dbx

### ISSUE THREAD

**Issue by Flickdm** [tianocore/edk2-pytool-extensions#488]
### What does the feature solve?

This feature would allow a user to audit the dbx contents on their system to determine what revocations exist on their system.

### Describe the solution

A tool grabs the dbx file from a system, and compares it against the public revocations found on UEFI.org from the csv file.  

### Have you considered any alternatives?

There are none.

**Comment by Javagedes** [comment]
Closed via #489
