### ISSUE TITLE
[Feature]: Conduct a Stuart user survey

### ISSUE THREAD

**Issue by makubacki** [tianocore/edk2-pytool-extensions#521]
### What does the feature solve?

In the TianoCore Tools & CI meeting this week it was reported that a number of developers do not like to use Stuart and prefer the shell scripts to build edk2. It is detrimental to the overall edk2 project to have two different ways of building (whether Stuart or another solution) due to maintenance, documentation overhead, etc.

Since this repo manages Stuart, I believe it is valuable to conduct a survey to collect user feedback about pain points using Stuart and prioritize feasible solutions to improve the user experience.

The goal from this ask is not to replace the shell scripts but to simply improve Stuart where possible.

### Describe the solution

Conduct a survey - on edk2 mailing list or in a [edk2 discussion post](https://github.com/tianocore/edk2/discussions) to gather feedback particularly for users on Linux.

**Comment by makubacki** [comment]
This was mentioned in the TianoCore Tools & CI meeting yesterday. I couldn't find a discussion created in response to this issue, so I created one here - https://github.com/tianocore/edk2/discussions/4369.

**Comment by Javagedes** [comment]
Closing as we have the referenced discussion https://github.com/tianocore/edk2/discussions/4369. along with https://github.com/tianocore/edk2-pytool-extensions/discussions/562 that we are currently monitoring for improvements to the usability of stuart
