### ISSUE TITLE
[Bug]: Build errors not reported in BaseTools

### ISSUE THREAD

**Issue by makubacki** [tianocore/edk2-pytool-extensions#539]
### Describe the Bug

@bcran reported the following in this GitHub discussion - https://github.com/tianocore/edk2/discussions/4369

When building `Edk2ToolsBuild.py`, @bcran removed the brotli submodule and received the following terminal output:

```
(venv) bcran@cube:~/src/uefi/tmp/edk2$ python3 BaseTools/Edk2ToolsBuild.py -t GCC5
SECTION - Init Self Describing Environment
SECTION - Loading Plugins
SECTION - Start Invocable Tool
Traceback (most recent call last):
  File "/home/bcran/src/uefi/tmp/edk2/BaseTools/Edk2ToolsBuild.py", line 177, in <module>
    main()
  File "/home/bcran/src/uefi/tmp/edk2/BaseTools/Edk2ToolsBuild.py", line 173, in main
    Edk2ToolsBuild().Invoke()
  File "/home/bcran/src/uefi/tmp/edk2/venv/lib/python3.11/site-packages/edk2toolext/base_abstract_invocable.py", line 236, in Invoke
    retcode = self.Go()
              ^^^^^^^^^
  File "/home/bcran/src/uefi/tmp/edk2/BaseTools/Edk2ToolsBuild.py", line 148, in Go
    raise Exception("Failed to build.")
Exception: Failed to build.
```

But did not receive helpful error output in `BaseTools/BaseToolsBuild/BASETOOLS_BUILD.txt` to identify the issue:

```
INFO - BrotliCompress.c:20:10: fatal error: ./brotli/c/common/constants.h: No such file or directory
INFO -    20 | #include "./brotli/c/common/constants.h"
INFO -       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
INFO - compilation terminated.
```

### What Python version are you using?

Python 3.10

### Reproduction steps

1. Build [Edk2ToolsBuild.py](https://github.com/tianocore/edk2/blob/master/BaseTools/Edk2ToolsBuild.py)
2. Remove the `brotli` submodule
3. Check the contents of `BaseTools/BaseToolsBuild/BASETOOLS_BUILD.txt`

### Expected behavior

`BaseTools/BaseToolsBuild/BASETOOLS_BUILD.txt` should have `ERROR` lines that help lead to the issue.

### Execution Environment

`GCC5` toolchain

### Pip packages

https://github.com/tianocore/edk2/blob/HEAD/pip-requirements.txt

**Comment by makubacki** [comment]
I tried this and agree that at least the GNUmakefile errors need to be propagated and logged as errors:

```
INFO - GNUmakefile:79: recipe for target 'BrotliCompress' failed
INFO - make[1]: *** [BrotliCompress] Error 2
INFO - make[1]: *** Waiting for unfinished jobs....
INFO - make[2]: Nothing to be done for 'all'.
INFO - make[2]: Leaving directory '/home/mikuback/src/edk2/BaseTools/Source/C/DevicePath'
INFO - make[1]: Leaving directory '/home/mikuback/src/edk2/BaseTools/Source/C'
INFO - GNUmakefile:19: recipe for target 'Source/C' failed
INFO - make: *** [Source/C] Error 2
111

**Comment by Javagedes** [comment]
@makubacki Edk2ToolsBuild.py does not utilize the compiler output scanner provided by edk2_logging. Due to this, it will need to be a two part fix. The first is adding in the regex rule to catch fatal errors, then adding the ability to scan compiler output to Edk2ToolsBuild.py.

I also think its better to expand on the gcc error to catch any fatal errors, but let me know if you don't agree. This is added in #547

**Comment by makubacki** [comment]
Thanks. I assumed Edk2ToolsBuild.py was already using the scanner in edk2_logging. Your plan to update both pieces sounds good. I'll leave feedback in #547 separately.

**Comment by Javagedes** [comment]
I have filed a bug with tianocore for the missing `scan_compiler_output()` function in Edk2ToolsBuild.py Base Tools 

https://bugzilla.tianocore.org/show_bug.cgi?id=4457

**Comment by Javagedes** [comment]
closing this as it no longer has any needed changes in edk2-pytool-extensions. The update is in Project Mu and a patch series has been approved to get it into EDK2.
