### ISSUE TITLE
[Bug]: Better clarify `-t`  usage

### ISSUE THREAD

**Issue by makubacki** [tianocore/edk2-pytool-extensions#540]
### Describe the Bug

Several instances of confusion around `-t` have been reported recently. For exmaple:

- https://github.com/tianocore/edk2/discussions/4286
- https://github.com/tianocore/edk2/discussions/4369

In `4286`:

- Command issued:
```
stuart_build -c EmulatorPkg/PlatformCI/PlatformBuild.py -t VS2019 -a X64 
```

- Output received:
```
ERROR - Traceback (most recent call last):
  File "C:\EDKII\edk2\.venv\lib\site-packages\edk2toolext\environment\uefi_build.py", line 145, in Go
    ret = self.SetEnv()
  File "C:\EDKII\edk2\.venv\lib\site-packages\edk2toolext\environment\uefi_build.py", line 478, in SetEnv
    "BUILD_OUT_TEMP"), target + "_" + self.env.GetValue("TOOL_CHAIN_TAG")), "Computed in SetEnv")
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

This was not sufficient to understand the problem.

### What Python version are you using?

Python 3.10

### Reproduction steps

1. Perform init steps in https://github.com/tianocore/edk2/blob/master/EmulatorPkg/PlatformCI/ReadMe.md
2. Run `stuart_build -c EmulatorPkg/PlatformCI/PlatformBuild.py -t VS2019 -a X64`

### Expected behavior

A message that clearly explains what is wrong and how to fix it.

**Comment by Javagedes** [comment]
I have created PR #545 which checks that TOOL_CHAIN_TAG and TARGET the first time they are used by `uefi_build`
