### ISSUE TITLE
[Feature]: Use pre-defined CI infrastructure variables to control log secret filtering

### ISSUE THREAD

**Issue by makubacki** [tianocore/edk2-pytool-extensions#565]
### What does the feature solve?

There's still occurrences of important information being filtered in local logs. For example, SHA256 hashes. This request is to reduce the amount of filtering that impacts common debug scenarios that use the logs.

### Describe the solution

Use pre-defined variables to detect if `stuart` execution is on a CI system. If not, then do not apply the log filter.

### Additional context

Pre-defined variable examples:

- [Predefined variable - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml)
- [Variables - GitHub Docs](https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables)

**Comment by Javagedes** [comment]
Looks like `TF_BUILD` for azure pipelines and `CI` for github actions are the most appropriate.
