### ISSUE TITLE
[Bug]: build dies if your project is not in Git

### ISSUE THREAD

**Issue by kkennett** [tianocore/edk2-pytool-extensions#595]
### Contact Details

kurtkennett@microsoft.com

### Describe the Bug

if you try to build a local project not in a git repo, the build will die at:

ile "<python path>\Lib\site-packages\edk2toolext\environment\self_describing_environment.py", line 51, in __init__
   details = repo_resolver.repo_details(self.workspace)

### What Python version are you using?

Python 3.11

### Reproduction steps

Private project not in Git.
ran platformbuild.py --setup

### Expected behavior

build shoudl continue and not require use of git or project to be in a git branch

### Execution Environment

Win11 cmd.exe

### Pip packages

Package                Version
---------------------- --------
antlr4-python3-runtime 4.11.1
attrs                  22.2.0
cffi                   1.15.1
cryptography           39.0.1
dtschema               2021.10
edk2-basetools         0.1.31
edk2-pytool-extensions 0.22.2
edk2-pytool-library    0.14.1
future                 0.18.2
gitdb                  4.0.10
GitPython              3.1.31
jsonschema             4.17.3
pefile                 2023.2.7
pip                    23.1.2
pycparser              2.21
pygit2                 1.11.1
pyrsistent             0.19.3
PyYAML                 6.0
regex                  2023.6.3
rfc3987                1.3.8
ruamel.yaml            0.17.21
semantic-version       2.10.0
setuptools             65.5.0
six                    1.16.0
smmap                  5.0.0
vboxapi                1.0
vboxapi                1.0
vboxapi                1.0

**Comment by Javagedes** [comment]
Talked offline. This particular issue was due to how we attempted to retrieve the repo's URL, which required an origin branch to exist, which is not necessarily true. This was release in v0.23.0, and per the pip requirements above, was only on v0.22.2. 

Confirmed that upgrading resolved the issue.
