### ISSUE TITLE
When the conf specifies a invalid file to build with, it shows a generic error

### ISSUE THREAD

**Issue by matthewfcarlson** [tianocore/edk2-pytool-extensions#63]
INFO - The system cannot find the path specified.
INFO -
INFO -
INFO - Build...
INFO -  : error 7000: Failed to execute command
INFO -  \..\..\Vc\Bin\nmake.exe /nologo tbuild [c:\git\uefi2018\Build\MsftIvanhoePkg\DEBUG_VS2015x86\IA32\MdePkg\Library\PeiPcdLib\PeiPcdLib]      
INFO -

**Comment by matthewfcarlson** [comment]
A better error message would be nice

**Comment by spbrogan** [comment]
this is mostly resolved in the change #92 .  With this change and the corresponding build plugins, they will confirm the path is valid if it is one of the supported tool chains and fail if not valid.
