### ISSUE TITLE
stuart_update logging needs cleaned up

### ISSUE THREAD

**Issue by spbrogan** [tianocore/edk2-pytool-extensions#8]
Example log looks like: 

SECTION - Init SDE
SECTION - Loading Plugins
SECTION - Start Invocable Tool
SECTION - First Update
SECTION - Retry Count: 1
SECTION - Summary
PROGRESS - Success

I would suggest First Update and Retry Count lines are not good.  

A pattern of doing Update and then if during the update a new ext_dep was found the next message can indicate that another update is needed due to environmental changes.

**Comment by matthewfcarlson** [comment]
I'll take a look at this today

**Comment by matthewfcarlson** [comment]
#21 tried to address this

**Comment by matthewfcarlson** [comment]
Fixed by #21
