### ISSUE TITLE
[Doc]: Broken links on "Building a Platform" page

### ISSUE THREAD

**Issue by brandonaut** [tianocore/edk2-pytool-extensions#855]
### Link to the documentation

https://github.com/tianocore/edk2-pytool-extensions/blob/master/docs/user/integrate/build.md#getting-started

### Description of Documentation Update

The following links on the page are broken (404):
- [Edk2InvocableSettingsInterface](https://github.com/tianocore/edk2-pytool-extensions/blob/master/api/edk2_invocable/#edk2toolext.edk2_invocable.Edk2InvocableSettingsInterface)
- [MultiPkgAwareSettingsInterface](https://github.com/tianocore/edk2-pytool-extensions/blob/master/api/invocables/edk2_multipkg_aware_invocable/#edk2toolext.invocables.edk2_multipkg_aware_invocable.MultiPkgAwareSettingsInterface)
- [SetupSettingsManager](https://github.com/tianocore/edk2-pytool-extensions/blob/master/api/invocables/edk2_setup/#edk2toolext.invocables.edk2_setup.SetupSettingsManager)
- [UpdateSettingsManager](https://github.com/tianocore/edk2-pytool-extensions/blob/master/api/invocables/edk2_update/#edk2toolext.invocables.edk2_update.UpdateSettingsManager)
- [BuildSettingsManager](https://github.com/tianocore/edk2-pytool-extensions/blob/master/api/invocables/edk2_ci_build/#edk2toolext.invocables.edk2_ci_build.CiBuildSettingsManager)

**Comment by Javagedes** [comment]
@brandonaut, thank you for reporting this. I've linked #856 to resolve this.
